### ISSUE TITLE
Dll references a specific version of KeePass 2

### ISSUE THREAD

**Issue by andrew-schofield** [andrew-schofield/keepass2-haveibeenpwned#1]
Alter the reference so it will work with any supported version of KeePass 2

**Comment by JPUnix** [comment]
What version of KeepPass is supported? I'm getting a version error also.

**Comment by andrew-schofield** [comment]
It should be supported by any version of KeePass 2 that uses the current API. The problem at the moment is that I've accidentally linked the compiled dll to a development build of KeePass so it won't load with any released version.
