### ISSUE TITLE
Cloudbleed checker hangs if entry URL field contains certain data

### ISSUE THREAD

**Issue by wellread1** [andrew-schofield/keepass2-haveibeenpwned#11]
The Cloudbleed checker hangs when an entry's URL field contains valid data that the plugin cannot process.  I have attached a screenshot of a cloudbleed checker hang on a valid path that is contained in an entry's URL field.

![cloudbleedhang](https://cloud.githubusercontent.com/assets/13069300/24317604/f695fc72-10b5-11e7-9939-fb4c22ca1fad.png)

Note: The forward slash used as path separator in the screenshot does not affect the outcome.

**Comment by andrew-schofield** [comment]
I'll have a look at this. The way I check for the part of the URL that I compare to the breach list isn't very clever, and I suspect this is the bit that is breaking.

**Comment by wellread1** [comment]
Thanks.

**Comment by andrew-schofield** [comment]
This bug should be fixed in v0.2.5
