### ISSUE TITLE
Can't identify the specific breach

### ISSUE THREAD

**Issue by jeff9315** [andrew-schofield/keepass2-haveibeenpwned#12]
The last breach in my list of breached entries is one for carnival.com. However, using the haveIBeenPwned website, I can't find an entry for carnival, nor one for the userid in my KeePass entry, nor one for any emails in that KeePass entry. It would be helpful if the breach list contained a column for the breach name as reported by HaveIBeenPwned.

Thanks ... Jeff

**Comment by andrew-schofield** [comment]
That's strange.

I can add some extra detail to the breach list which should hopefully clarify why this entry was detected.

**Comment by jeff9315** [comment]
That would be GREAT!!

**Comment by andrew-schofield** [comment]
You should see the breach name in the output window if you update to v0.2.6.
I'm working on getting a little more information about the breach into a tooltip when you hover over the entry in the list.

**Comment by jeff9315** [comment]
Great. Thanks!!

**Comment by jeff9315** [comment]
OK ... I have an entry for Carnival Cruise Lines (https://www.carnival.com). The breach is for "nival". So, it looks like you might have a regex slightly wrong. Having the Breach name really helps a lot.

Thansk ... Jeff

**Comment by andrew-schofield** [comment]
That's really helpful. I'll take a look at the url checking logic and should be able to get this fixed.

**Comment by andrew-schofield** [comment]
OK, I've fixed the url checking code in this commit 3eff8d904340dbb4fe4ab7d74fc695944d236e4e
It will be included in the next release.
