### ISSUE TITLE
Exclude Deleted entries or show Column "Group"

### ISSUE THREAD

**Issue by OLLI-S** [andrew-schofield/keepass2-haveibeenpwned#14]
You really did an amazing plugin that helps a lot.
Both checkers find some entries but I recognized that some of these entries are in the folder "Recycle Bin" (I have a German name of that folder so I hope it is called "Recycle Bin").

It would be good to have in the dialog a 3rd checkbox called "Exclude Deleted entries".
This way less entries are found.
In addition you can add a new column "Group" in the results dialog that shows the Group of the entry.

**Comment by andrew-schofield** [comment]
v0.2.7 now shows groups in the breached entry list.

**Comment by OLLI-S** [comment]
Perfect, thank you!
