### ISSUE TITLE
Conflicts with KeeAnywhere

### ISSUE THREAD

**Issue by andrew-quinn** [andrew-schofield/keepass2-haveibeenpwned#18]
Hey there Mr. Schofield - just giving you a heads up that the HIBP plugin causes the KeeAnywere not to be able to sync with Google Drive. Not a huge issue at all, but something to be aware of. I can follow up with details if you ever wanna zap this bug.

**Comment by andrew-schofield** [comment]
I just tried using KeeAnywhere without HIBP installed and it doesn't work either.

**Comment by andrew-schofield** [comment]
I believe this was a bug in KeeAnywhere.

KeePass 2.36, KeeAnywhere 1.4.1 and HIBP 0.3.1 seem to place nicely together (tested saving to google drive).
