### ISSUE TITLE
2.9.1 ... no download?

### ISSUE THREAD

**Issue by jeff9315** [andrew-schofield/keepass2-haveibeenpwned#22]
I just downloaded 2.9.1. It doesn't seem to be downloading the HaveIBeenPwned file. I cancelled it after about 5 minutes. I'm not sure whether it's a problem with this version of the plugin or with the HaveIBeenPwned site or just my impatience. This is on Windows 10 (I tried rebooting but that didn't help).

Anyone else having this problem?

Thanks ... Jeff

**Comment by andrew-schofield** [comment]
Not just you, its not working for me either. Looking into it now.

**Comment by andrew-schofield** [comment]
Got the fix, should be up shortly.
