### ISSUE TITLE
multiple instances of cloudbleed.txt

### ISSUE THREAD

**Issue by eg0rych** [andrew-schofield/keepass2-haveibeenpwned#32]
Hi,

After starting the plugin single time I am observing multiple instances of the cloudbleed.txt file in the file system. All files are identical in size and have exactly the same timestamp from today.

See the screenshot

Please advise
![2017-10-18_14-51-43](https://user-images.githubusercontent.com/32899257/31715267-257d169a-b414-11e7-9da9-2596c0dcd0da.png)

**Comment by andrew-schofield** [comment]
Is it creating a new file every time you run the cloudbleed checker?

The file paths there look very odd.

**Comment by eg0rych** [comment]
1) Removed all cloudbleed.txt files from my file system (the plugin remained installed as is).
2) in Keepass Tools executed scan for breaches based on site/service, with default options + "Check all supported breaches" enabled
3) again, 16 occurrences with weird paths were created, same size 71769240 bytes, and the timestamps of the creation are totally identical to a single second.

**Comment by eg0rych** [comment]
Update: it looks like it's physically the same file (deleted once and all are gone), but search engines give this weird result due to links in file system appearing as folders and the way they scan it through. Total Commander reports 16 occurrences; Windows Explorer search 26 (in Windows 10 - 1607); but apparently it's just 1 physical file versus multiple nested references.

So I take it this is no bug, at least not on the plugin side. Apologies for the confusion.

**Comment by andrew-schofield** [comment]
I'm going to close this issue as I don't think its a plugin bug.
