### ISSUE TITLE
Version is wrong

### ISSUE THREAD

**Issue by realmar** [andrew-schofield/keepass2-haveibeenpwned#35]
The `VERSION` file indicates version 1.2.3 though in releases only version 1.2.2 is available. This results in Keepass2 always showing the "Update Check" window on start even that there are no updates.

**Comment by andrew-schofield** [comment]
v1.2.3 has been added to releases. The most recent version is always available here: https://github.com/andrew-schofield/keepass2-haveibeenpwned/blob/master/HaveIBeenPwned.plgx
