### ISSUE TITLE
Password changed date pulling top date in version history, not latest

### ISSUE THREAD

**Issue by tastyratz** [andrew-schofield/keepass2-haveibeenpwned#37]
When running the utility against my DB I am seeing it say password changed date incorrectly.
For example, 1 entry says it was changed 5/25/2014 but that's the first version/date in history. This was changed 4 more times since then including 2017. That date is not reflected and the entry is incorrectly showing as breached.

Also,
This same example account is showing 3 times with the same password changed date on the list for the same breach date/name.

This example account has been updated since the breach date and shouldn't even show at all. This is not the only account I have doing this.

**Comment by andrew-schofield** [comment]
Can you enable the built-in "password last changed date" column in KeePass and see what date it shows for these entries? The code used should be the same.

**Comment by tastyratz** [comment]
I just enabled the column and the date for last password modification matches the date on the list, you are correct. I must have misinterpreted and be mistaken. Thank you, I'll close the bug. Sorry about that.
