### ISSUE TITLE
Ignore Expired entries

### ISSUE THREAD

**Issue by OLLI-S** [andrew-schofield/keepass2-haveibeenpwned#42]
I have some entries that are marked as "Expired" (Expiry Date is in the past) so KeePass shows a red "X" instead of the favicon.
These entries are also not considered when I press the Auto Type Hotkey.

In HIBP these expired entries are reported because the URL was hacked.
So please add an option "[X] Ignore any expired entries" that is checked by default.

**Comment by andrew-schofield** [comment]
Fixed in #65
