### ISSUE TITLE
Unhandled exception when proxy requires Authorisation

### ISSUE THREAD

**Issue by godeater** [andrew-schofield/keepass2-haveibeenpwned#49]
Hi there,

I use KeePass from my office PC, which is connected to the internet via a proxy which requires authentication. At the moment, the plugin causes a .NET exception as below :

![image](https://user-images.githubusercontent.com/1461/41893804-d4b4a996-7914-11e8-9431-0c0db0672406.png)

I've tried overriding the proxy in KeePass itself to use a local CNTLM instance I use for other software which doesn't understand how to authenticate with our proxy infrastructure, however it seems the plugin sticks to only using the system proxy, and therefore always generates this exception.

**Comment by andrew-schofield** [comment]
Should be fixed in #63
