### ISSUE TITLE
Kayo.Moe breach

### ISSUE THREAD

**Issue by jeff9315** [andrew-schofield/keepass2-haveibeenpwned#54]
Is the Kayo.Moe breach included in this list? The breach name isn't included in the columns. And on the HIBP website, the offline downloads don't look like they contain September data yet. And I'm not sure whether your lookup is online or through a download and offline lookup.

Thanks ... Jeff

**Comment by andrew-schofield** [comment]
As mentioned above, this plugin merely checks the haveibeenpwned website, so if it's there it will be included in the breach lists you see in KeePass.
