### ISSUE TITLE
Bug regarding "Recycle Bin"

### ISSUE THREAD

**Issue by jeff9315** [andrew-schofield/keepass2-haveibeenpwned#55]
Thank you very much for this plugin.

I have several subfolders under the Recycle Bin for entries I need to do certain things with before deleting them. Even though I have "Ignore Deleted Entries", the entries in subfolders of the recycle bin still get checked.

Thanks ... Jeff

**Comment by Kolbi** [comment]
Can confirm this bug.

**Comment by andrew-schofield** [comment]
Fixed in 6a1047e0533921cac3e01c0d2c6d42f44835dfe0.
