### ISSUE TITLE
Don't "lock" main window while showing Breached Entries

### ISSUE THREAD

**Issue by Svish** [andrew-schofield/keepass2-haveibeenpwned#57]
Would it be possible to, when showing the Breached Entries result dialog, to not "lock" the main window? I.e. so that I can still do stuff in KeePass while showing the results at the same time?

After having run this, I for example find stuff that is horribly outdated that I can just delete, but while the dialog is open I'm only able to edit an entry.

Also, while this dialog is open, I can't use KeePass to login anywhere... 🤔

**Comment by andrew-schofield** [comment]
Fixed in #64
