### ISSUE TITLE
Stuck on "Getting HaveIBeenPwned breach list..."

### ISSUE THREAD

**Issue by internationils** [andrew-schofield/keepass2-haveibeenpwned#58]
Hello,
I just installed it on Ubuntu (both the DLL and the PLGX), and initially had the problem shown here with both plugins:
https://github.com/andrew-schofield/keepass2-haveibeenpwned/issues/46
It would be good to have the solution (see also https://askubuntu.com/questions/127796/where-is-keepass2-plugins-directory ) documented for this plugin as a lot of linux users will likely run into this.

Once the plugin ran (both seem to work), the progress gets stuck on "Getting HaveIBeenPwned breach list..." After leaving it overnight, still no progress. There is no progress indicator running
Any ideas on whats wrong, or on where to get more details?
Thanks...

**Comment by internationils** [comment]
After following the steps on 
https://github.com/andrew-schofield/keepass2-haveibeenpwned/issues/47
I'm now also stuck on
https://github.com/andrew-schofield/keepass2-haveibeenpwned/issues/56

**Comment by andrew-schofield** [comment]
Added a note in b6696bf6bbab7f33ae5f110f2e01f64abe4ca4df
