### ISSUE TITLE
[Keepass 2.4.0 Linux] Error: SecureChannelFailure (The authenticator or decryption has failed.)

### ISSUE THREAD

**Issue by zaggynl** [andrew-schofield/keepass2-haveibeenpwned#67]
> HaveIBeenPwned Checker
> 
> Error: SecureChannelFailure (The authenticator or decryption has failed.) 

appears after pressing " Check for breaches".

This occurs with both dll and plgx version.

**Comment by andrew-schofield** [comment]
How old is your mono installation? Older versions appear to have a bug which breaks TLS 1.2 which haveibeenpwned requires.

**Comment by zaggynl** [comment]
mono --version
Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)

**Comment by zaggynl** [comment]
Resolved after installing through Ubuntu 18.04 PPA per https://www.mono-project.com/download/stable/, thanks!
