### ISSUE TITLE
Wrong version shown in Keepass for 1.3.0

### ISSUE THREAD

**Issue by timkimber** [andrew-schofield/keepass2-haveibeenpwned#74]
Just installed v1.3.0 but the plugins window shows the installed version as v1.2.4.0.  

I'm sure I've installed the latest version - I downloaded and installed twice just to check I hadn't made a mistake and Keepass has stopped telling me a new version is available so the plugin thinks it's the latest version, just the old version number is displayed.

**Comment by dervitti** [comment]
This is peculiar. other users do not seem to have the problem. update to 1.3.1?

**Comment by timkimber** [comment]
Just updated to 1.3.1.0 and it's worked fine - probably user error, thanks for checking.
