### ISSUE TITLE
Not working on Linux/Mono

### ISSUE THREAD

**Issue by Generator** [andrew-schofield/keepass2-haveibeenpwned#8]
On linux with mono only minimizes the windows.

**Envoriment:**
Archlinux
keepass - 2.35
mono - 4.8.0.495

**Comment by andrew-schofield** [comment]
I'm not sure I understand. Are you saying that when you click on the menu item to run the HIBP check it minimizes KeePass and doesn't do anything else?

**Comment by Generator** [comment]
Yes, nothing happens, the plugins starts checking entries, when finish only minimizes the main window.  

With the mono upgrade (4.8.0.495) HIBP kinda works! But sets almost all entries as expired, even entries not related to any site, like entries with only information or local accounts.

Cloudbleed doesn't work either, only minimizes the main window after checking entries, with no entries marked as expired.

**Comment by andrew-schofield** [comment]
I see the minimising bug on Windows as well. I think on mono the messagebox isn't appearing when it detects a breach, so it looks like nothing is happening.

I'll add a separate issue for creating a results dialog which should hopefully resolve that.

As for expiring entries with no URLs etc, that is odd as these *should* be ignored. I'll dig a little deeper into that one.

**Comment by andrew-schofield** [comment]
Try 0.2.1 to see if this improves the minimise behaviour. The problem may be that if you click on other windows while the progress dialog is shown, KeePass waits until it is finished before relinquishing focus.

**Comment by Generator** [comment]
I've tried not clicking anywhere, main window open.

I'll try that version as soon as possible and maybe I'll create an Archlinux package if there's no major issues.

**Comment by Generator** [comment]
HIBP now works properly also the new download windows shows the download progress.   
Cloudbleed not even downloads data (sorted_unique_cf.txt). I see no traffic when i use "Cloudbleed Checker"

**Comment by andrew-schofield** [comment]
The timeout on the httpclient may be too low to download the cloudbleed data file. I'll increase the timeout which should fix the problem.

**Comment by andrew-schofield** [comment]
I've increased the timeout in 0.2.2.1 to 30 minutes (from 10).

**Comment by Generator** [comment]
Cloudbleed downloads 71MB (from 151.101.192.133) but the "Downloading Cloudbleed datafile" remains after download with no progress. And no entries are checked.
![captura de ecra_2017-03-10_23-42-50](https://cloud.githubusercontent.com/assets/44146/23817468/4b6f09f8-05eb-11e7-92a9-f9077d0d731d.png)

![captura de ecra_2017-03-10_23-40-34](https://cloud.githubusercontent.com/assets/44146/23817455/2fdd850c-05eb-11e7-8959-9dd890ae4de6.png)

**Comment by andrew-schofield** [comment]
The lack of progress relates to #3, however it shouldn't just hang at that point.
Has it actually downloaded the file anywhere? Does %PROGRAMDATA% map to a sensible location on Linux when using mono?

**Comment by Generator** [comment]
Honestly i don't know, according to this [page](https://www.jimrich.sk/2015/01/18/environment-specialfolder-on-windows-linux-and-os-x/) _System.Environment.SpecialFolder.CommonApplicationData_ points to _/usr/share_  
Can't be write by user, keepass stores his cache in _$HOME/.local/share/KeePass/_ (_System.Environment.SpecialFolder.LocalApplicationData_)

I've created a log see if it helps
[keepass.log.gz](https://github.com/andrew-schofield/keepass2-haveibeenpwned/files/842958/keepass.log.gz)

**Comment by andrew-schofield** [comment]
Try 0.2.4.1. I've changed the download location for mono to `LocalApplicationData`, so this should get past the hanging issue.

**Comment by Generator** [comment]
Now its working, both checkers working with "Breached Entries" window.

**Comment by andrew-schofield** [comment]
Great. I'll close this issue then.
