### ISSUE TITLE
HaveIbeenPwned API breaks the plugin

### ISSUE THREAD

**Issue by panosladas** [andrew-schofield/keepass2-haveibeenpwned#82]
This great plugin doesn't seem to be working anymore when the API needs to be used. Does anyone recommend any solution to this issue?

**Comment by jakob-ledermann** [comment]
If you mean the API changes on HIBP to Version 3 you can try to download the plgx from my pull request #83 , especially if you already have a valid api key, as I was unable to test with a working api Key.
I think you can find further details in #80 as it started to discuss the issue before the changes went live.

**Comment by andrew-schofield** [comment]
Fixed in #83
