### ISSUE TITLE
Increased Size of 1.3.2?

### ISSUE THREAD

**Issue by ccoenen** [andrew-schofield/keepass2-haveibeenpwned#84]
Checking the 1.3.2 plgx, I found that it was nearly 10 times as big as 1.3.1 and the previous versions. Does anyone know why?

**Comment by andrew-schofield** [comment]
Fixed in v1.3.3. The plgx unintentionally included the keepass executable in v1.3.2

**Comment by ccoenen** [comment]
thanks for the quick reply :-)
