### ISSUE TITLE
Where do I put the API Key for HIBP?

### ISSUE THREAD

**Issue by markoer73** [andrew-schofield/keepass2-haveibeenpwned#87]
As the title suggests.  I have been unable to see where in KeePass I should put the API key from HIBP for username/password checks - I could not find a plugin configuration or a KeePass one.

Thanks!

**Comment by andrew-schofield** [comment]
Currently you need to create a new entry in your data based called "hibp-apikey", and set the password to your API key.

**Comment by andrew-schofield** [comment]
I've added a note to the readme about where to put the API key. Fixed in v1.3.5
