### ISSUE TITLE
Release v1.3.5 reports incorrect version (v1.3.4)

### ISSUE THREAD

**Issue by vbojan** [andrew-schofield/keepass2-haveibeenpwned#88]
Release v1.3.5 still reports version as v1.3.4 so KeePass update check reports there is a newer version available (v1.3.5).

**To Reproduce**
1. Go to 'Help'
2. Click on 'Check for Updates'
3. See "Status", "Installed" and "Available"

**Expected behavior**
Plugin should pass correct version to KeePass so it doesn't display information about newer version being available.

**Comment by cybermcm** [comment]
same here...

**Comment by dantek12345** [comment]
Same for me - prompts every morning that a new version is available - but if you download the latest plugin it makes no difference - still reports as the old version.
Has the plugin file on the download page actually been updated? Or have you just forgotten to update the version number within the plugin?

**Comment by andrew-schofield** [comment]
Confirmed, it appears the plgx file on the release page, and in the repository don't have the new version information embedded in the plugin. They do have the updated functionality, just not the correct version.

I've temporarily reverted the VERSION file back to 1.3.4, so the update checker will no longer report that there is a new version.

**Comment by andrew-schofield** [comment]
I've just released v1.3.6 which actually contains the correct version number in the plugin file. No other changes.
