### ISSUE TITLE
How do you remove "have I been pwned" from all entries?

### ISSUE THREAD

**Issue by Chaython** [andrew-schofield/keepass2-haveibeenpwned#93]
How do you remove "have I been pwned" from all entries?
I no longer wish to use the plugin, I removed the plugin but there's leftover string field for have I been pwned.
How can I remove the string field from all entries?

**Comment by andrew-schofield** [comment]
This plugin doesn't modify your existing entries in any way. Did you maybe use this plugin https://github.com/mihaifm/HIBPOfflineCheck as that does appear to add a new field to your entries?

**Comment by Chaython** [comment]
Perhaps I have, sorry. I think I looked at this one, but I'm worried about anything calling out from a password manager so looked for an offline version.
