### ISSUE TITLE
How te remove the 'Have I been Pwned'-field in my database?

### ISSUE THREAD

**Issue by pven** [andrew-schofield/keepass2-haveibeenpwned#95]
I removed this plugin a while ago. But I was never able to delete the 'Have I been Pwned'-field in my database. I can do it manually, but it is a lot of work for >400 entries. I searched for documentation, but was nog able to find it yet.

Is there an ease way to get this done?

Thanks!

**Comment by andrew-schofield** [comment]
I suspect this is a duplicate of #93

This plug-in doesn't alter your keepass entries at all, so I think you've probably installed one of the other hibp plugins for keepass, not this one.

**Comment by pven** [comment]
You are right. Thanks!
